#!/bin/ksh
# Find hosts on LAN
#
NETWORK="192.168.1"               
TIMEOUT="0.4"                     

typeset -i i

echo -e "\nPinging addresses 1 to 255\n"

let i=1
while (( i <255 )) ;do
	ip=$NETWORK.$i
	# timeout used here eliminate waiting for nonexistant hosts
	timeout $TIMEOUT ping -c 1 $ip > /dev/null
	if [ $? == '0' ]
	then
	echo $ip exists
	fi
	let i++
done
