#!/bin/bash
##############################################
# Create a note or append an existing note.  #
#                                            #
# If no argument is passed, script will open #
# and append to existing file or create a    #
# new file for editing based on the current  #
# month.                                     #
#       Example: jan.note                    #
#                                            #
# Passing an argument will attempt to load   #
# that filename if it exists or create new   #
#       Example: filename.note               #
##############################################

# Configure variables for your preferred terminal emulator settings 
TERMINAL="xterm"
OPTIONS="-rv -fa 'Monospace' -fs 12"

# Configure your save path here
DIR="Documents/notes"

# Get the date and format it some
MONTH=$(date +%b | tr -s "[A-Z]" "[a-z]")

cd $DIR
if [ $# -lt 1 ]
then
echo -e '\n' $(date +%e\ %b\ %Y\ \@\ %H:%M)'\n====================[Void-Linux-X201]\n' >> $MONTH.note
$TERMINAL $OPTIONS -e vim -c "normal! Gzz" $MONTH.note
else
echo -e '\n' $(date +%e\ %b\ %Y\ \@\ %H:%M)'\n====================[Void-Linux-X201]\n' >> $1.note
$TERMINAL $OPTIONS -e vim -c "normal! Gzz" $1.note
fi

