#!/usr/bin/bash
# Find hosts on LAN
# Edit variables to suit your needs
###################################
NETWORK="192.168.1"               #
SECS="0.1"                        #
###################################

typeset -i i

echo -e "\nPinging addresses 1 to 255\n"
for (( i = 1 ;  i<255 ; i++ )) ;
    do
            ip=$NETWORK.$i
            ping -c 1 -W $SECS $ip >/dev/null
            if [ $? == '0' ]
                    then
                    echo $ip exists
            fi
    done
